# Generated by Django 5.1.6 on 2025-02-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date_of_payment",
            field=models.DateField(verbose_name="Дата оплаты"),
        ),
    ]
