# Generated by Django 5.1.7 on 2025-03-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_payment_payment_amount_payment_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="payment_amount",
        ),
    ]
